//
// Created by user on 10/23/25.
//

#ifndef ASSIGNMENT_2_RECURSION_IN_AN_RDF_GRAPH_MIKECODE124_MAIN_RDFOBJECT_H
#define ASSIGNMENT_2_RECURSION_IN_AN_RDF_GRAPH_MIKECODE124_MAIN_RDFOBJECT_H


class RDFOBject {

};


#endif //ASSIGNMENT_2_RECURSION_IN_AN_RDF_GRAPH_MIKECODE124_MAIN_RDFOBJECT_H